version: '3.4'

services:
  helsiapi:
    image: ${DOCKER_REGISTRY-}helsiapi
    build:
      context: .
      dockerfile: HelsiApi/Dockerfile
    container_name: helsiapi
    networks:
      - helsinetwork
    ports:
      - "10000:80"
    depends_on:
      - db
      - es
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elastic_search
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - helsinetwork
    ports:
      - "19200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana_elastic_search
    ports:
        - "15601:5601"
    environment:
        - ELASTICSEARCH_URL=http://localhost:9200

    networks:
        - helsinetwork
    depends_on:
        - es
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: sql-server
    networks:
      - helsinetwork
    ports:
      - "11433:1433"
    environment:
      MSSQL_PID: "Developer"
      SA_PASSWORD: "123456789_secret!23" 
      ACCEPT_EULA: "Y"
       
volumes:
    esdata:
        driver: local

networks:
  helsinetwork:
     driver: bridge